#!/usr/bin/env python3
"""Apply and verify the declared inbound links for reachsocial.co.

WHY THIS EXISTS (ClickUp 86bc9bp1f, 2026-09-29)
-----------------------------------------------
Cross-linking on this site was a periodic BACKFILL, not a publish step. A page
shipped, nothing linked to it, and someone ran a cleanup days later. Measured
2026-09-29, four independent sources agreed:

  * SEMrush issue 213 went 0 -> 2 `is_new`, naming exactly the two newest pages
  * `grep -rl` over the tree found only blog/index.html linking to the new post
  * GSC `referring_urls` for that post was JUST the sitemap
  * git showed c50a537 (09-08) and aa243bc (09-19) were both one-off backfills,
    and 8eeafbc (09-22) shipped after the last one and got nothing

SEMrush's own counters said it out loud: issue 213 read `fixed: 21` next to
`new: 2`. The task filed on 09-08 was closed as a fix; it was a cleanup. At one
post a week plus case-study batches that is 50-80 pages a year each starting
life invisible, and both newest pages were the only two un-indexed URLs on the
site.

THE DURABILITY HALF, which is the part a backfill can never solve
-----------------------------------------------------------------
`casestudies/<slug>/index.html` is GENERATED by the case-study-reach skill from
a ClickUp task. A hand-edited link there is destroyed the next time that task is
rendered, silently. So even a perfectly executed backfill decays. Declaring the
link and re-applying it after render is the only thing that holds.

Blog posts are different and already fine: their source of truth is
`blog/_generator/posts/<slug>.body.html`, which render_post.py reads rather than
overwrites. Blog-to-blog links belong in the body source. This tool exists for
the generated case studies, and verifies the body-source ones without touching
them.

USAGE
  python crosslink.py --verify     # exit 1 if any declared link is missing
  python crosslink.py --apply      # insert/refresh every declared link
  python crosslink.py --list       # show what is declared

Run --apply after ANY case-study render, and --verify before any push.
"""
import argparse
import json
import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
ROOT = Path(__file__).resolve().parent
REGISTRY = ROOT / "crosslinks.json"

# Sentinel comments make the block identifiable and the operation idempotent.
# Without them, re-applying appends a duplicate paragraph every run, and --verify
# cannot tell a real declared link from prose that happens to mention the URL.
START = "<!-- crosslink:start {target} -->"
END = "<!-- crosslink:end {target} -->"


def load():
    d = json.loads(REGISTRY.read_text(encoding="utf-8"))
    return d.get("links", []), d.get("verify_also", [])


def block_for(entry):
    return (f'    {START.format(target=entry["target"])}\n'
            f'    {entry["html"]}\n'
            f'    {END.format(target=entry["target"])}')


def find_section_end(html: str, anchor: str):
    """Index of the closing </section> of the section containing `anchor`.

    Returns None rather than guessing. A wrong insertion point is worse than a
    loud failure: it puts a link somewhere nobody reviewed.
    """
    m = re.search(re.escape(anchor), html)
    if not m:
        return None
    end = html.find("</section>", m.end())
    return end if end != -1 else None


def apply_one(entry, dry=False):
    path = ROOT / entry["file"]
    if not path.exists():
        return "MISSING-FILE", f"{entry['file']} does not exist"
    html = path.read_text(encoding="utf-8")
    start_s = START.format(target=entry["target"])
    end_s = END.format(target=entry["target"])

    if start_s in html and end_s in html:
        i, j = html.index(start_s), html.index(end_s) + len(end_s)
        current = html[i:j]
        fresh = block_for(entry).strip()
        if current.strip() == fresh:
            return "OK", "already present and current"
        if not dry:
            path.write_text(html[:i] + fresh + html[j:], encoding="utf-8")
        return "REFRESHED", "block text changed, replaced in place"

    # Link present but NOT in a sentinel block: a hand edit from before this tool.
    # Adopt it rather than adding a second copy of the same link.
    if entry["target"] in html:
        return "UNMANAGED", ("link already present as a hand edit, NOT wrapped in "
                             "sentinels. It will be lost on the next re-render. "
                             "Remove the hand-edited line, then re-run --apply.")

    pos = find_section_end(html, entry["anchor"])
    if pos is None:
        return "NO-ANCHOR", f"could not find a section containing {entry['anchor']!r}"
    if not dry:
        path.write_text(html[:pos] + block_for(entry) + "\n  " + html[pos:], encoding="utf-8")
    return "INSERTED", f"added before the </section> holding {entry['anchor']!r}"


def verify_one(entry):
    path = ROOT / entry["file"]
    if not path.exists():
        return False, "file does not exist"
    html = path.read_text(encoding="utf-8")
    if entry["target"] not in html:
        return False, "declared link is ABSENT"
    if "anchor" in entry:  # a managed entry should also carry its sentinels
        if START.format(target=entry["target"]) not in html:
            return False, ("link present but NOT sentinel-wrapped, so it is a hand "
                           "edit and will be wiped by the next re-render")
    return True, "present"


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--apply", action="store_true")
    g.add_argument("--verify", action="store_true")
    g.add_argument("--list", action="store_true")
    ap.add_argument("--dry-run", action="store_true", help="with --apply, change nothing")
    a = ap.parse_args()

    links, also = load()

    if a.list:
        print(f"{len(links)} managed + {len(also)} asserted-only\n")
        for e in links:
            print(f"  [managed] {e['target']}\n      in {e['file']}  (after {e['anchor']!r})")
        for e in also:
            print(f"  [assert ] {e['target']}\n      in {e['file']}")
        return 0

    if a.apply:
        print(f"crosslink --apply{' --dry-run' if a.dry_run else ''}  ({len(links)} declared)\n")
        bad = 0
        for e in links:
            status, msg = apply_one(e, dry=a.dry_run)
            if status in ("NO-ANCHOR", "MISSING-FILE", "UNMANAGED"):
                bad += 1
            print(f"  {status:<12} {e['file']}\n               {msg}")
        print(f"\n{'=' * 68}\nRESULT: {len(links) - bad} applied/current, {bad} need attention")
        return 1 if bad else 0

    # --verify
    print(f"crosslink --verify  ({len(links)} managed + {len(also)} asserted)\n")
    failed = []
    for e in links + also:
        ok, msg = verify_one(e)
        print(f"  {'PASS' if ok else 'FAIL'}  {e['target']}\n        in {e['file']} - {msg}")
        if not ok:
            failed.append(e)
    print("=" * 68)
    if failed:
        print(f"RESULT: FAIL - {len(failed)} declared inbound link(s) missing or fragile.")
        print("Run `python crosslink.py --apply`. Do NOT push an orphaned page: that is")
        print("exactly the failure 86bc9bp1f exists to stop, and it cost two un-indexed URLs.")
        return 1
    print(f"RESULT: PASS - all {len(links) + len(also)} declared inbound links present.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
